@startuml IeeeBibliographicItem

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BibliographicItem <<biblio>>{

}

class IeeeBibliographicItem {
  +title: FormattedString
  +documentStatus: IeeeDocumentStatus
  +committee: IeeeCommittee[0..*]
}

class IeeeCommittee {
  +type: String
  +name: String
  +chair: String[0..1]
}

class IeeeDocumentStatus{
  +status: IeeeStatusType
}

enum IeeeDocumentStatusType <<enumeration>>{
  Active
  Inactive
}

'******* NOTES ********************************************************

'******* CLASS RELATIONS **********************************************
BibliographicItem <|-- IeeeBibliographicItem

IeeeBibliographicItem <-- IeeeDocumentStatus

IeeeBibliographicItem <-- IeeeCommittee

Citation <|-- IeeeDocumentCitation
IeeeBibliographicItem <-- IeeeDocumentCitation

IeeeDocumentStatus <-- IeeeDocumentStatusType

@enduml
